language: java
env:
  global:
    - MAVEN_OPTS="-Xmx512m"
jdk:
  - oraclejdk8
# https://docs.travis-ci.com/user/firefox/
addons:
  firefox: latest
# https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
branches:
  except:
    - /^dukecon-server-[0-9].*$/
script:
  - mvn -U test
cache:
  directories:
  - $HOME/.m2